# Generated by Django 6.0.4 on 2026-04-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cartmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
